Add Random Color Node
JacquesLucke/animation_nodes pull request #1532
Opened 2020-09-16 02:22 UTC by kdsin23

Add Random Color Node

2020-09-16 19:37 UTC, OmarEmaraDev requested changes
Looks good. But remember to update the CHANGELOG and add the node to the menu.

2020-09-17 02:29 UTC, kdsin23 commented
> Looks good. But remember to update the CHANGELOG and add the node to the menu.

Thanks, i will add it soon

2020-09-17 02:38 UTC, kdsin23 commented
why i updated the CHNGELOG.md, then appeared ''This branch has conflicts that must be resolved"? how to solve?

2020-09-17 11:31 UTC, OmarEmaraDev commented
Merge upstream master like we said before, then add the CHANGELOG entry.

2020-09-17 14:31 UTC, OmarEmaraDev requested changes

2020-09-17 14:31 UTC, OmarEmaraDev commented on animation_nodes/nodes/color/random_color.py
> +    bl_idname = "an_RandomColor"
`an_RandomColor` -> `an_RandomColorNode`

2020-09-17 15:38 UTC, kdsin23 commented on animation_nodes/nodes/color/random_color.py
> +    bl_idname = "an_RandomColor"
Ok!

2020-09-18 16:48 UTC, OmarEmaraDev approved these changes
Thanks!

2020-09-18 16:49 UTC, merged