Add Evaluate Transforms FCurves node.
JacquesLucke/animation_nodes pull request #1843
Opened 2022-04-03 14:34 UTC by jekor

Implements #1842 

Also add Frame output to Evaluate FCurve node.

2022-04-03 21:06 UTC, OmarEmaraDev requested changes
Thanks for working on this!

I would leave the `outFrame` output out of this patch. I haven't looking at it, but it should be submitted as a different patch regardless.

Also, make sure to add your changes to the CHANGELOG file.

2022-04-03 21:06 UTC, OmarEmaraDev commented on animation_nodes/nodes/fcurve/evaluate_transforms_fcurves.py
> +        yield "scale = Vector(tuple(t['scale']))"
`AN.utils.math.composeMatrix` doesn't really expect vectors, so you can just pass the lists for the scale and location directly, leaving the Euler as is.

2022-04-03 21:06 UTC, OmarEmaraDev commented on animation_nodes/nodes/fcurve/evaluate_transforms_fcurves.py
> +        yield "t = {'location': [0,0,0], 'rotation_euler': [0,0,0], 'scale': [1,1,1]}"
Use a more meaningful name here. `transforms` maybe.

2022-04-03 21:06 UTC, OmarEmaraDev commented on animation_nodes/nodes/fcurve/evaluate_transforms_fcurves.py
> +class EvaluateFCurveNode(bpy.types.Node, AnimationNode):
Looks like you forgot to update the name of the class.

2022-04-03 21:06 UTC, OmarEmaraDev commented on animation_nodes/nodes/fcurve/evaluate_transforms_fcurves.py
> +    bl_label = "Evaluate Transforms FCurves"
I would use "Evaluate FCurves Transforms" instead.

2022-04-04 03:18 UTC, jekor commented
Updated.

2022-04-04 19:17 UTC, OmarEmaraDev requested changes
Two small things and this will be ready to go.

2022-04-04 19:17 UTC, OmarEmaraDev commented on animation_nodes/nodes/fcurve/evaluate_fcurves_transforms.py
> +        items = frameTypeItems, update = executionCodeChanged)
The update method should be `propertyChanged` now that we no longer change the execution code.

2022-04-04 19:17 UTC, OmarEmaraDev commented on animation_nodes/nodes/fcurve/evaluate_fcurves_transforms.py
> +        transforms = {"location": [0,0,0], "rotation_euler": [0,0,0], "scale": [1,1,1]}
Spaces after commas.

2022-04-09 07:01 UTC, OmarEmaraDev approved these changes
Looks good. Thanks!

2022-04-09 07:02 UTC, merged