Mesh custom attributes
JacquesLucke/animation_nodes pull request #1931
Opened 2023-11-06 13:13 UTC by 3DSinghVFX

This patch will fix the Custom Attributes Nodes for Blender3.6.

2023-11-06 19:27 UTC, OmarEmaraDev commented
I am not particularly happy that we are using EdgeIndicesList for that. We should probably add an Int2List type and a corresponding socket. Then provide implicit conversion between edges indices and this new list. We will not provide any kind of processing support, just reading of those attributes and conversion to edge indices list.

2023-11-08 04:59 UTC, 3DSinghVFX commented
@OmarEmaraDev Okay. So, where I can add the New Int2List type?

2023-11-08 06:56 UTC, OmarEmaraDev commented
It can be added in the `special_list_types.json` file, it should be mostly similar to `EdgeIndicesList` in that file. Don't forget to import it in `data_structures/__init__.py`. See for instance: https://github.com/JacquesLucke/animation_nodes/commit/692ba52ed3a4830b451b1ba4af8f640cf432af10, except we probably don't need to add a type for int2.

2023-11-30 20:21 UTC, OmarEmaraDev requested changes

2023-11-30 20:21 UTC, OmarEmaraDev commented on animation_nodes/nodes/mesh/insert_custom_attribute.py
> +            _data = createEdgeIndices(amount, _indices1, _indices2)
This seems a bit too complicated. Can we just create a virtual list for int2?
See the `virtual_clist_types.json` file. And maybe add Int2 to `math/vector.pxd` to make things easier.

2023-12-04 14:18 UTC, 3DSinghVFX commented on animation_nodes/data_structures/lists/special_list_types.json
> +        "Additional Methods" : "__indices_list_functions.src",
Okay.

2023-12-11 19:36 UTC, OmarEmaraDev commented
I would just move the conversion code to the conversion file to fix this:
```
diff --git a/animation_nodes/data_structures/lists/special_list_types.json b/animation_nodes/data_structures/lists/special_list_types.json
index d9ad1cb4..8038a019 100644
--- a/animation_nodes/data_structures/lists/special_list_types.json
+++ b/animation_nodes/data_structures/lists/special_list_types.json
@@ -96,11 +96,12 @@
         "Type" : "Int2",
         "Buffer Type" : "int",
         "Equals" : "not memcmp(&(\\1), &(\\2), sizeof(Int2))",
-        "Try Conversion" : "if len(value) == 2: target.v1, target.v2 = value[0], value[1]\nelse: raise TypeError(\"length has to be 2\")",
-        "To PyObject" : "(value.v1, value.v2)",
+        "Try Conversion" : "setInt2(target, value)",
+        "To PyObject" : "toPyInt2(value)",
         "Additional Methods" : "",
         "Declarations" : [
-            "from ... math.vector cimport Int2"
+            "from ... math.vector cimport Int2",
+            "from ... math.conversion cimport setInt2, toPyInt2"
         ]
     }
 }
diff --git a/animation_nodes/math/conversion.pxd b/animation_nodes/math/conversion.pxd
index 70771910..df36678f 100644
--- a/animation_nodes/math/conversion.pxd
+++ b/animation_nodes/math/conversion.pxd
@@ -1,7 +1,7 @@
 from . color cimport Color
 from . euler cimport Euler3
 from . quaternion cimport Quaternion
-from . vector cimport Vector2, Vector3, Vector4
+from . vector cimport Vector2, Vector3, Vector4, Int2
 from . matrix cimport Matrix3, Matrix4, Matrix3_or_Matrix4
 
 cdef Matrix4 toMatrix4(value) except *
@@ -22,6 +22,10 @@ cdef Vector4 toVector4(value) except *
 cdef setVector4(Vector4* v, value)
 cdef toPyVector4(Vector4* v)
 
+cdef Int2 toInt2(value) except *
+cdef setInt2(Int2* v, value)
+cdef toPyInt2(Int2* v)
+
 cdef Euler3 toEuler3(value) except *
 cdef setEuler3(Euler3* e, value)
 cdef toPyEuler3(Euler3* e)
diff --git a/animation_nodes/math/conversion.pyx b/animation_nodes/math/conversion.pyx
index b8a45c64..c8cb7b64 100644
--- a/animation_nodes/math/conversion.pyx
+++ b/animation_nodes/math/conversion.pyx
@@ -52,6 +52,20 @@ cdef setVector4(Vector4* v, value):
 cdef toPyVector4(Vector4* v):
     return Vector((v.x, v.y, v.z, v.w))
 
+cdef Int2 toInt2(value) except *:
+    cdef Int2 v
+    setInt2(&v, value)
+    return v
+
+cdef setInt2(Int2* v, value):
+    if len(value) != 2:
+        raise TypeError("element is not a 2D integer vector")
+    v.x = value[0]
+    v.y = value[1]
+
+cdef toPyInt2(Int2* v):
+    return (v.x, v.y)
+
 
 # Matrices
 ##########################################################
```

2023-12-23 13:40 UTC, OmarEmaraDev approved these changes

2023-12-23 13:40 UTC, merged